// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingPlatform.DataAccess;

namespace TrainingPlatform.DataAccess.Migrations
{
    [DbContext(typeof(TrainingPlatformContext))]
    [Migration("20220127103748_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Repeat")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "martwy ciąg z kettlebell ustawiamy ciało w dokładnie taki sam sposób, jak przy podejściu do sztangi. Stajemy na szerokości bioder lub nieco szerzej, stopy kierując minimalnie na zewnątrz. Napinamy mięśnie brzucha i pośladów, ściągamy łopatki.",
                            Link = "https://www.youtube.com/watch?v=-rtEvBD7haM&list=PLafWxHJll3dV12nuEWKrWfgqxbr1EtHbZ&index=1",
                            Name = "MARTWY CIĄG ODWAŻNIKIEM KULOWYM",
                            Repeat = 20,
                            Series = 10,
                            Weight = 32
                        },
                        new
                        {
                            Id = 2,
                            Description = "Stań w rozkroku szerszym niż na szerokość bioder, kolana lekko zgięte – chwyć kettlebell w obie dłonie i wykonaj lekki wymach w tył, by odważnik znalazł się między nogami (nawet lekko za nimi), a następnie wypychając biodra do przodu, wykonaj wyrzut kettlebell przed siebie na wysokość klatki piersiowej. Wróć do pozycji wyjściowej. Ważne jest utrzymanie prostych pleców, wyprostowanych ramion.Swing może być wykonywany także na jedną rękę.",
                            Link = "https://www.youtube.com/watch?v=_NGSfoPgdgQ&list=PLafWxHJll3dV12nuEWKrWfgqxbr1EtHbZ&index=2",
                            Name = "SWING ODWAŻNIKIEM KULOWYM",
                            Repeat = 18,
                            Series = 8,
                            Weight = 28
                        },
                        new
                        {
                            Id = 3,
                            Description = "Trening nóg z kettlebell możesz rozpocząć właśnie od tego ćwiczenia. Stań w szerszym rozkroku i chwyć kettlebell, przyciągając go do klatki piersiowej, po czym wykonaj przysiad, nie zmieniając jego pozycji. Pamiętaj o tym, by linia kolan nie przekraczała linii palców.",
                            Link = "https://www.youtube.com/watch?v=03B7-XSO1MI&list=PLafWxHJll3dV12nuEWKrWfgqxbr1EtHbZ&index=4",
                            Name = "PRZYSIAD Z ODWAŻNIKIEM",
                            Repeat = 16,
                            Series = 6,
                            Weight = 24
                        },
                        new
                        {
                            Id = 4,
                            Description = "Stań w szerokim rozkroku, chwyć kettlebell jedną ręką i wykonaj zamach, by znalazł się między nogami. Następnie wypchnij biodra i wyrzuć go przed siebie – gdy znajdzie się na wysokości klatki piersiowej, szybko zegnij rękę w łokciu, by odważnik znalazł się blisko ciała. Łokieć powinien być przyklejony do klatki piersiowej, a odważnik na zewnętrznej stronie dłoni. Druga ręka powinna być wyprostowana w bok, pomagając utrzymać równowagę. Wróć do pozycji wyjściowej.",
                            Link = "https://www.youtube.com/watch?v=0LrZ3Tl8aSg&list=PLafWxHJll3dV12nuEWKrWfgqxbr1EtHbZ&index=6",
                            Name = "ZARZUT ODWAŻNIKIEM KULOWYM JEDNORĄCZ CLEAN",
                            Repeat = 14,
                            Series = 4,
                            Weight = 22
                        },
                        new
                        {
                            Id = 5,
                            Description = "Wstawanie tureckie (TGU) to ćwiczenie, które pomaga rozwinąć mobilność i stabilność w barkach, a statyczne obciążenie rozwija ich siłę. Dodatkowo wzmacnia stożki rotatorów poprzez przeciwdziałanie rotacji kettla wokół nadgarstka. TGU aktywuje wszystkie mięśnie brzucha, wzmacnia mięśnie głębokie oraz mięśnie obręczy kończyny dolnej. ",
                            Link = "https://www.youtube.com/watch?v=303ejRDjZX0&list=PLafWxHJll3dV12nuEWKrWfgqxbr1EtHbZ&index=7",
                            Name = "TURECKIE WSTAWANIE Z ODWAŻNIKIEM KULOWYM TGU",
                            Repeat = 12,
                            Series = 2,
                            Weight = 20
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ćwiczenie jest zbliżone do Military Pressu, jednak różni się dynamiką. Rozstaw szeroko nogi, chwyć kettlebell w jedną dłoń, po czym wykonaj wymach w tył i wyciśnij go do przodu. Nie zatrzymuj się jednak w okolicy klatki piersiowej – od razu przenieś wyprostowaną rękę nad głowę. Kettlebell w ostatniej fazie ruchu powinien znaleźć się za dłonią. Wykonaj na obie strony ciała.",
                            Link = "https://www.youtube.com/watch?v=GG3e2MZS02w&list=PLafWxHJll3dV12nuEWKrWfgqxbr1EtHbZ&index=11",
                            Name = "RWANIE ODWAŻNIKIEM KULOWYM",
                            Repeat = 14,
                            Series = 5,
                            Weight = 34
                        });
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.ExercisePlan", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.HasKey("PlanId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExercisePlans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            ExerciseId = 1
                        },
                        new
                        {
                            PlanId = 1,
                            ExerciseId = 2
                        },
                        new
                        {
                            PlanId = 1,
                            ExerciseId = 3
                        },
                        new
                        {
                            PlanId = 2,
                            ExerciseId = 4
                        },
                        new
                        {
                            PlanId = 2,
                            ExerciseId = 5
                        },
                        new
                        {
                            PlanId = 3,
                            ExerciseId = 6
                        });
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trening A01"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trening A02"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trening A03"
                        });
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.PlanUser", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlanId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PlanUsers");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            UserId = 1
                        },
                        new
                        {
                            PlanId = 2,
                            UserId = 1
                        },
                        new
                        {
                            PlanId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Adam",
                            HashedPassword = "HO9i39jP5fA0/UOJ+l2PaKJS3wVsqZir7mck2NsuwBU=",
                            LastName = "Kozioł",
                            Salt = "2euNApDf3kkT/KNA6bkVpg==",
                            Username = "Adams"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Adam",
                            HashedPassword = "HO9i39jP5fA0/UOJ+l2PaKJS3wVsqZir7mck2NsuwBU=",
                            LastName = "Kozioł",
                            Salt = "2euNApDf3kkT/KNA6bkVpg==",
                            Username = "Adams"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Marek",
                            HashedPassword = "hKB8ZsIF4QPJyOmhjzN2xG0x3N3rwMPUVhmaS53qt5k=",
                            LastName = "Nowak",
                            Salt = "fsCKGWaGb3mcTnrRIu90pw==",
                            Username = "NowaM"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Artur",
                            HashedPassword = "Jv2JFt9d0OtEjbUZeLGBNqey3ZXeA3bztSo+FA1c9Qw=",
                            LastName = "Mess",
                            Salt = "lFYVXoG9W/w87+bNVXbTXg==",
                            Username = "Mace"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Jan",
                            HashedPassword = "kQsi7XDcqN9XLqnPZhwMjEtixruI/HotgmvaExfYCvg=",
                            LastName = "Kowalski",
                            Salt = "l6YlFQkg2G4yiKCwyeyhcg==",
                            Username = "kowal"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("TrainingPlatform.DataAccess.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingPlatform.DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.ExercisePlan", b =>
                {
                    b.HasOne("TrainingPlatform.DataAccess.Entities.Exercise", "Exercise")
                        .WithMany("ExercisePlans")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingPlatform.DataAccess.Entities.Plan", "Plan")
                        .WithMany("ExercisePlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.PlanUser", b =>
                {
                    b.HasOne("TrainingPlatform.DataAccess.Entities.Plan", "Plan")
                        .WithMany("PlanUsers")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingPlatform.DataAccess.Entities.User", "User")
                        .WithMany("PlanUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.Exercise", b =>
                {
                    b.Navigation("ExercisePlans");
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.Plan", b =>
                {
                    b.Navigation("ExercisePlans");

                    b.Navigation("PlanUsers");
                });

            modelBuilder.Entity("TrainingPlatform.DataAccess.Entities.User", b =>
                {
                    b.Navigation("PlanUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
